/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author augusto.ojeda
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
       
        FlatLightLaf.setup();
        initComponents();
        this.setLocationRelativeTo(null);
        initContent();
        
       
        
        
    }
    
    private void initContent() {
     ShowJPanel(new Inicio());
        
    }
    
    private void ShowJPanel(JPanel p){
    
       
        p.setSize(860, 400);
        p.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panel_latera = new javax.swing.JPanel();
        factura_btn = new javax.swing.JButton();
        inicio_btn = new javax.swing.JButton();
        articulo_btn = new javax.swing.JButton();
        stock_btn = new javax.swing.JButton();
        clientes_btn = new javax.swing.JButton();
        proveedores_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_horizontal = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        panel_latera.setBackground(new java.awt.Color(33, 93, 251));
        panel_latera.setMaximumSize(new java.awt.Dimension(210, 700));
        panel_latera.setPreferredSize(new java.awt.Dimension(210, 550));

        factura_btn.setBackground(new java.awt.Color(3, 55, 192));
        factura_btn.setForeground(new java.awt.Color(255, 255, 255));
        factura_btn.setText("FACTURAS");
        factura_btn.setBorderPainted(false);
        factura_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factura_btnActionPerformed(evt);
            }
        });

        inicio_btn.setBackground(new java.awt.Color(3, 55, 192));
        inicio_btn.setForeground(new java.awt.Color(255, 255, 255));
        inicio_btn.setText("INICIO");
        inicio_btn.setBorderPainted(false);
        inicio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_btnActionPerformed(evt);
            }
        });

        articulo_btn.setBackground(new java.awt.Color(3, 55, 192));
        articulo_btn.setForeground(new java.awt.Color(255, 255, 255));
        articulo_btn.setText("ARTICULOS");
        articulo_btn.setBorderPainted(false);
        articulo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articulo_btnActionPerformed(evt);
            }
        });

        stock_btn.setBackground(new java.awt.Color(3, 55, 192));
        stock_btn.setForeground(new java.awt.Color(255, 255, 255));
        stock_btn.setText("STOCK");
        stock_btn.setBorderPainted(false);
        stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_btnActionPerformed(evt);
            }
        });

        clientes_btn.setBackground(new java.awt.Color(3, 55, 192));
        clientes_btn.setForeground(new java.awt.Color(255, 255, 255));
        clientes_btn.setText("CLIENTES ");
        clientes_btn.setBorderPainted(false);
        clientes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes_btnActionPerformed(evt);
            }
        });

        proveedores_btn.setBackground(new java.awt.Color(3, 55, 192));
        proveedores_btn.setForeground(new java.awt.Color(255, 255, 255));
        proveedores_btn.setText("REPORTES");
        proveedores_btn.setBorderPainted(false);
        proveedores_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedores_btnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoP.png"))); // NOI18N

        javax.swing.GroupLayout panel_lateraLayout = new javax.swing.GroupLayout(panel_latera);
        panel_latera.setLayout(panel_lateraLayout);
        panel_lateraLayout.setHorizontalGroup(
            panel_lateraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lateraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1))
            .addComponent(inicio_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(factura_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(articulo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(stock_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientes_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(proveedores_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_lateraLayout.setVerticalGroup(
            panel_lateraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lateraLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(inicio_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(factura_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(articulo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(stock_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(clientes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(proveedores_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panel_horizontal.setBackground(new java.awt.Color(72, 116, 232));

        javax.swing.GroupLayout panel_horizontalLayout = new javax.swing.GroupLayout(panel_horizontal);
        panel_horizontal.setLayout(panel_horizontalLayout);
        panel_horizontalLayout.setHorizontalGroup(
            panel_horizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panel_horizontalLayout.setVerticalGroup(
            panel_horizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        contenido.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(panel_latera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_horizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_latera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_horizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factura_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factura_btnActionPerformed
        ShowJPanel(new Factura());
    }//GEN-LAST:event_factura_btnActionPerformed

    private void inicio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_btnActionPerformed
        ShowJPanel(new Inicio());
    }//GEN-LAST:event_inicio_btnActionPerformed

    private void articulo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articulo_btnActionPerformed
        ShowJPanel(new Articulo());
    }//GEN-LAST:event_articulo_btnActionPerformed

    private void stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_btnActionPerformed
        ShowJPanel(new Stock());
    }//GEN-LAST:event_stock_btnActionPerformed

    private void clientes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes_btnActionPerformed
        ShowJPanel(new Clientes());
    }//GEN-LAST:event_clientes_btnActionPerformed

    private void proveedores_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedores_btnActionPerformed
       ShowJPanel(new Reportes());
    }//GEN-LAST:event_proveedores_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton articulo_btn;
    private javax.swing.JButton clientes_btn;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton factura_btn;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton inicio_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_horizontal;
    private javax.swing.JPanel panel_latera;
    private javax.swing.JButton proveedores_btn;
    private javax.swing.JButton stock_btn;
    // End of variables declaration//GEN-END:variables
}
