/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC.Vista;
import MVC.Controlador.ControladorMarca;
import MVC.Controlador.ControladorPais;
import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author augusto.ojeda
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        FlatLightLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaTrabajo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_Articulos = new javax.swing.JMenuItem();
        MI_Marcas = new javax.swing.JMenuItem();
        MI_Paises = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout AreaTrabajoLayout = new javax.swing.GroupLayout(AreaTrabajo);
        AreaTrabajo.setLayout(AreaTrabajoLayout);
        AreaTrabajoLayout.setHorizontalGroup(
            AreaTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        AreaTrabajoLayout.setVerticalGroup(
            AreaTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jMenu1.setText("Gestion");

        MI_Articulos.setText("Articulos");
        jMenu1.add(MI_Articulos);

        MI_Marcas.setText("Marcas");
        MI_Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_MarcasActionPerformed(evt);
            }
        });
        jMenu1.add(MI_Marcas);

        MI_Paises.setText("Paises");
        MI_Paises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_PaisesActionPerformed(evt);
            }
        });
        jMenu1.add(MI_Paises);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Facturacion");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTrabajo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTrabajo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_PaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_PaisesActionPerformed
        IF_Pais internalFrame = new IF_Pais();
        ControladorPais C_Pais = new ControladorPais(internalFrame);
        AreaTrabajo.add(C_Pais);
        C_Pais.setVisible(true);
    }//GEN-LAST:event_MI_PaisesActionPerformed

    private void MI_MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_MarcasActionPerformed
        IF_Marca internalFrame = new IF_Marca();
        ControladorMarca C_Marca = new ControladorMarca(internalFrame);
        AreaTrabajo.add(C_Marca);
        C_Marca.setVisible(true);
    }//GEN-LAST:event_MI_MarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane AreaTrabajo;
    private javax.swing.JMenuItem MI_Articulos;
    private javax.swing.JMenuItem MI_Marcas;
    private javax.swing.JMenuItem MI_Paises;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
